/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32h735g_discovery.h"
#include "stm32h735g_discovery_conf.h"
#include "stm32h735g_discovery_lcd.h"
#include "stm32h735g_discovery_ts.h"
#include "stm32h7xx_hal.h"
#include <stdint.h>

#include "stm_slint_platform.h"
#include "bsp_init.h"

#include "printer.h"

int main(void) {

  bsp_init();
  InitTouchScreen();

  init_slint(LCD_LAYER_0_ADDRESS, LCD_LAYER_1_ADDRESS, LCD_DEFAULT_WIDTH,
             LCD_DEFAULT_HEIGHT);
  BSP_LED_On(LED1);
  run_printer();
  BSP_LED_On(LED2);

  while (1) {
    ;
  }
}
